module: ColorSlider
module_name: ColorSlider
author: Sachin Patel
author_url: https://gizmosachin.com
github_url: https://github.com/gizmosachin/ColorSlider
github-file-prefix: https://github.com/gizmosachin/ColorSlider/tree/master
readme_path: ./source/README.md
root-url: https://gizmosachin.github.io/ColorSlider/docs
xcodebuild-arguments: -scheme,ColorSlider
module-version: master
exclude: []
copyright: '© 2016 [Sachin Patel](http://gizmosachin.com).'
swift_version: 2.2
